FROM nginx:alpine
RUN apk add --no-cache openssl && \
    mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/nginx/ssl/smartlogix.key \
      -out /etc/nginx/ssl/smartlogix.crt \
      -subj "/CN=44.199.171.235"
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80 443
