spring.application.name=bff
server.port=8085

# ✅ Azure AD - Validacion JWT (Microsoft Entra ID / IDaaS)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/57bd7ed4-95cb-4813-b649-72cfc68924db/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/57bd7ed4-95cb-4813-b649-72cfc68924db/discovery/keys

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.inventario.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventario.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventario.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario.waitDurationInOpenState=10s

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.metadata-map.swagger=http://localhost:8085/swagger-ui.html
eureka.instance.metadata-map.health=http://localhost:8085/actuator/health
eureka.instance.metadata-map.description=BFF - JWT Azure AD + Circuit Breaker
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.status-page-url=http://localhost:8085/actuator/info
eureka.instance.health-check-url=http://localhost:8085/actuator/health
eureka.instance.home-page-url=http://localhost:8085/swagger-ui.html

management.info.env.enabled=true
info.app.name=BFF - SmartLogix
info.app.description=BFF con JWT Azure AD + Circuit Breaker
info.app.version=2.0.0
info.app.puerto=8085
