spring.application.name=eureka-server
server.port=8761

# El servidor no se registra a si mismo ni busca otros registros
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Recomendado para entorno local/demo: acelera el deregistro de instancias caidas
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
